### Get gas stations
GET http://localhost:5002/api/v1/gas-stations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3Y2E1ZWJjLTcxODYtNDMwOC1hZGExLTk4OTEzY2FhZGMxNiIsInVzZXJuYW1lIjoiYWVtb29vb29uIiwiZW1haWwiOiJhZW1vb29vb25AZ21haWwuY29tIiwiaWF0IjoxNzEzNDMyMTQ3LCJleHAiOjE3MTM0MzkzNDd9.tRwcjZV24XVkzjvnv78InAGUdxsFEp9xN6QgsT0MF6Y
