# 使用 Ubuntu 20.04 镜像作为基础镜像
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# 更新软件包索引并安装基本依赖
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    nodejs \
    npm \
    python3 \
    python3-pip \
    make \
    gcc \
    g++ \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install && npm rebuild bcrypt --build-from-source

COPY . .

EXPOSE 5002

CMD ["node", "index.js"]
